// Copyright: Ankitects Pty Ltd and contributors
// License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

syntax = "proto3";

option java_multiple_files = true;

package anki.mcat;

import "anki/generic.proto";

service McatService {
  rpc GetTopicMastery(generic.Empty) returns (TopicMasteryList);
  rpc GetTopicMasteryOne(TopicMasteryRequest) returns (TopicMastery);
}

service BackendMcatService {}

message TopicMasteryRequest {
  string topic_id = 1;
}

message TopicMastery {
  string topic_id = 1;
  uint32 cards_total = 2;
  uint32 cards_seen = 3;
  uint32 good_or_easy_count = 4;
  float avg_retrievability = 5;
  bool performance_unlocked = 6;
}

message TopicMasteryList {
  repeated TopicMastery entries = 1;
}
